---
- name: Run Atomic Red Team tests on Windows targets
  hosts: atomic_targets_windows
  gather_facts: false
  vars:
    atomic_runner: powershell
  roles:
    - atomic_redteam
  tags: [atomic, attack]

- name: Run Atomic Red Team tests on Linux/macOS targets
  hosts: atomic_targets_linux
  gather_facts: false
  vars:
    atomic_runner: atomic_operator
  roles:
    - atomic_redteam
  tags: [atomic, attack]
