---
# --- OpenSCAP (host-level CIS/STIG checks) ---
oscap_datastream: "/usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml"
oscap_profile: "xccdf_org.ssgproject.content_profile_cis"
oscap_packages:
  - openscap-scanner
  - scap-security-guide
ansible_password: Appleman123!@#

results_root: "{{ playbook_dir }}/../../results"   # where raw tool output lands on the CONTROL NODE

